"""add pfp url

Revision ID: 3d6f8675c8ef
Revises: 94ee36c8f08a
Create Date: 2023-02-24 11:35:49.332037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6f8675c8ef'
down_revision = '94ee36c8f08a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_trackers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pfp_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_trackers', schema=None) as batch_op:
        batch_op.drop_column('pfp_url')

    # ### end Alembic commands ###
