"""Initial models migrations

Revision ID: 213d1f998bda
Revises: 
Create Date: 2023-02-22 19:51:57.687355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '213d1f998bda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_trackers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('fid', sa.Integer(), nullable=True),
    sa.Column('following_fids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('following_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('follower_fids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('follower_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_trackers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('fid', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=75), nullable=True),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('bio', sa.String(length=160), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trackees',
    sa.Column('fid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('fid'),
    sa.UniqueConstraint('fid')
    )
    op.create_table('tracker_managers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('trackee_fid', sa.Integer(), nullable=True),
    sa.Column('tracker_fid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracker_managers')
    op.drop_table('trackees')
    op.drop_table('profile_trackers')
    op.drop_table('follow_trackers')
    # ### end Alembic commands ###
